RED	= \033[0;31m
NC	= \033[0m

all:
	@python3 main.py "input.txt"

test1:
	@echo "\n$(RED)--- Running tests - Test 1 ---$(NC)"
	@python3 main.py "input_test_1.txt"

test2:
	@echo "\n$(RED)--- Running tests - Test 2 ---$(NC)"
	@python3 main.py "input_test_2.txt"

testp:
	@echo "\n$(RED)--- Running tests - Test Small ---$(NC)"
	@python3 main.py "input_test_p.txt"